You can define Flyway configuration for each datasource. The following example demonstrates using it:

[source, yaml]
.src/main/resources/application.yml
----
include::{flywaytests}/groovy/io/micronaut/configuration/dbmigration/flyway/FlywaySpec.groovy[tag=yamlconfig,indent=0]
----

<1> Disable schema DDL creation.
<2> Define flyway configuration under `flyway.datasources` key.
<3> Configure flyway configuration for `default` data source.
<4> The migrations directory is `src/main/resources/databsemigrations`.


In that directory you need to include all your migrations, for example:

[source,sql]
.resources/databasemicrations/V1__create-books-schema.sql
----
include::{flywaytests}/resources/databasemigrations/V1__create-books-schema.sql[indent=0]
----

There are several options available for configuration:

include::{includedir}configurationProperties/io.micronaut.configuration.dbmigration.flyway.FlywayConfigurationProperties.adoc[]

NOTE: By default Micronaut will configure Flyway to use the datasources defined under `datasources` configuration key. If
you want to use a different datasource you need to define the properties `+flyway.datasources.*.url+`, `+flyway.datasources.*.user+`
and `+flyway.datasources.*.password+`.
