This section will outline any breaking changes between major or milestone releases as well as detail any new features that have been added.

== 2.0.0.M2

* By default look for migrations in Flyway default location: `src/main/resources/db/migration`.
* Add support for GraalVM.

== 2.0.0.M1

* Upgrade to Micronaut 2.0.0.M3.
* Upgrade to Flyway 6.4.3
* Rename package `io.micronaut.configuration.dbmigration.flyway` to `io.micronaut.flyway`.

== 1.2.0

* Fix issue with Micronaut Data https://github.com/micronaut-projects/micronaut-data/issues/441[#441].
* Upgrade to Micronaut 1.3.3.

== 1.1.0

* Added support for GORM.
* Upgrade to Micronaut 1.1.3.

== 1.0.0

* Underlying implementation has been changed to run the migrations as soon as possible. If you are not extending or overriding the API, there are no functional changes to note.


== 1.0.0.RC3

* Upgrade to Micronaut 1.0.4.
* Upgrade to Flyway 5.2.4.

== 1.0.0.RC2

* Add configuration property to clean the schema before running the migrations.
* Fire events after clean the schema and after run the migrations.

== 1.0.0.RC1

* First public release.
