plugins {
    id("io.micronaut.build.internal.flyway-base")
    id("io.micronaut.build.internal.java-base")
    id("org.graalvm.buildtools.native")
}

dependencies {
    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mnTest.micronaut.test.junit5)
    testRuntimeOnly(mnLogging.logback.classic)
    testImplementation(mnTest.junit.jupiter.engine)
    testRuntimeOnly(mnTest.junit.platform.launcher)
}

tasks.named("test") {
    useJUnitPlatform()
}
graalvmNative {
    toolchainDetection = false
    metadataRepository {
        version = "0.3.12"
        enabled = true
    }
    binaries {
        all {
            resources.autodetect()
        }
        configureEach {
            buildArgs("--initialize-at-build-time=org.junit.platform.commons.logging.LoggerFactory\$DelegatingLogger")
        }
    }
}

dependencies {
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
}
