
There is also support for running Flyway migrations when using GORM.

1.- Add the dependency:

dependency:micronaut-hibernate-gorm[groupId="io.micronaut.configuration"]

2.- You also need at least one class annotated with `@grails.gorm.annotation.Entity` to trigger the migrations.
[source, groovy]
.src/main/groovy/example/Book.groovy
----
include::{flywaytests}/groovy/io/micronaut/flyway/docs/Book.groovy[tag=bookImport]

include::{flywaytests}/groovy/io/micronaut/flyway/docs/Book.groovy[tag=annotation]
include::{flywaytests}/groovy/io/micronaut/flyway/docs/Book.groovy[tag=domain]
----

3.- Then it is necessary to configure GORM datasource:

[source, yaml]
.src/main/resources/application.yml
----
include::{flywaytests}/groovy/io/micronaut/flyway/docs/GormSpec.groovy[tag=yamlconfig,indent=0]
----

<1> Definition of the first data source in GORM. The name it's `default` and it can't be changed.
<2> Disable schema DDL creation.
<3> Define flyway configuration under `flyway.datasources` key.
<4> Define flyway configuration for the `default` datasource.
<5> Enable the flyway migrations for the `default` datasource.


=== Multiple Data sources

It is also possible to configure Flyway migrations with multiple data sources when using GORM:

[source, yaml]
.src/main/resources/application.yml
----
include::{flywaytests}/groovy/io/micronaut/flyway/docs/GormMultipleDataSourcesSpec.groovy[tag=yamlconfig,indent=0]
----

<1> Definition of the first data source in GORM. The name it's `default` and it can't be changed.
<2> Name of the additional data source.
<3> Enable the flyway migrations for the `books` datasource.
<4> Enable the flyway migrations for the `default` datasource.


NOTE: For more information about how to configure GORM, take a look at the http://gorm.grails.org/latest/hibernate/manual/index.html[documentation].

