
There is also support for running Flyway migrations when using GORM.

1.- Add the dependency:

dependency:micronaut-hibernate-gorm[groupId="io.micronaut.groovy"]

2.- You also need at least one class annotated with `@grails.gorm.annotation.Entity` to trigger the migrations.
[source, groovy]
.src/main/groovy/example/Book.groovy
----
include::{flywaytests}/groovy/io/micronaut/flyway/docs/Book.groovy[tag=bookImport]

include::{flywaytests}/groovy/io/micronaut/flyway/docs/Book.groovy[tag=annotation]
include::{flywaytests}/groovy/io/micronaut/flyway/docs/Book.groovy[tag=domain]
----

3.- Then it is necessary to configure GORM datasource:

[configuration]
----
include::{flywaytests}/groovy/io/micronaut/flyway/docs/GormSpec.groovy[tag=yamlconfig,indent=0]
----

- `dataSource` defines the first data source in GORM. The name is `default` and can't be changed.
- `dbCreate` set to `none` disables schema DDL creation.
- Define flyway configuration under `flyway.datasources`. The default datasource is configured and enabled in this example.


=== Multiple Data sources

It is also possible to configure Flyway migrations with multiple data sources when using GORM:

[configuration]
----
include::{flywaytests}/groovy/io/micronaut/flyway/docs/GormMultipleDataSourcesSpec.groovy[tag=yamlconfig,indent=0]
----

- `dataSource` defines the first data source in GORM. The name is `default` and can't be changed.
- `dataSources.books` names an additional data source.
- Define flyway configurations under `flyway.datasources.<name>`. Both datasources are configured and enabled in this example.


NOTE: For more information about how to configure GORM, take a look at the http://gorm.grails.org/latest/hibernate/manual/index.html[documentation].

