You can define Flyway configuration for each datasource. The following example demonstrates using it:

[configuration]
----
include::{flywaytests}/groovy/io/micronaut/flyway/docs/FlywaySpec.groovy[tag=yamlconfig,indent=0]
----

- `hibernate.hbm2ddl.auto` set to `none` disables schema DDL creation.
- Define flyway configuration under `flyway.datasources`. The default datasource is configured and enabled in this example under `datasources.default`, `jpa.default` and  and `flyway.datasources.default`

NOTE: You need to put the migrations in Flyway default directory `src/main/resources/db/migration`. If you want to
modify the default directory or add more, you need to set the property `flyway.datasources.default.locations`.
For example:

[configuration]
----
flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:databasemigrations
        - classpath:other
----

- `locations` configures Flyway to look for migrations in the directories `src/main/resources/databasemigrations` and
`src/main/resources/other`.


Now, in the migration directory you can include your migrations:

[source,sql]
.src/main/resources/db/migration/V1__create-books-schema.sql
----
include::{flywaytests}/resources/db/migration/V1__create-books-schema.sql[indent=0]
----

NOTE: Starting with Micronaut `1.1.3` it is not necessary to define the `jpa` configuration if you only want to run the migrations but not actually use JPA.

== Run migrations manually

If you need more control to decide when the migrations are executed it is possible to configure the application like this:

[configuration]
----
flyway:
  enabled: true
  datasources:
    default:
      enabled: false
----
- `flyway.enabled` needs to be `true`
- `datasources.*.enabled` set to `false` can disable flyway migrations for specific datasources

Now you can inject the `FlywayMigrator` bean and call manually the method `run` to execute the migrations when you want.
