You can define Flyway configuration for each datasource. The following example demonstrates using it:

.src/main/resources/application.yml
[configuration]
----
datasources:
  default:
    url: 'jdbc:h2:mem:flywayDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'
jpa:
  default:
    packages-to-scan:
      - 'example.micronaut'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
----

- Disable schema DDL creation with `jpa.default.properties.hibernate.hbm2ddl.auto` set to 'none'
- Define flyway configuration under `flyway.datasources` key.
- Configure flyway configuration for `default` datasource under `datasources.default` and `jpa.default`
- Enable the flyway migrations for the `default` datasource under `flyway.datasources.default`

NOTE: You need to put the migrations in Flyway default directory `src/main/resources/db/migration`. If you want to
modify the default directory or add more, you need to set the property `flyway.datasources.default.locations`.
For example:

[configuration]
----
flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:databasemigrations
        - classpath:other
----
- The `locations` properties configure Flyway to look for migrations in the directories `src/main/resources/databasemigrations` and `src/main/resources/other`.


Now, in the migration directory you can include your migrations:

[source,sql]
.src/main/resources/db/migration/V1__create-books-schema.sql
----
include::{flywaytests}/resources/db/migration/V1__create-books-schema.sql[indent=0]
----

NOTE: Starting with Micronaut `1.1.3` it is not necessary to define the `jpa` configuration if you only want to run the migrations but not actually use JPA.

== Run migrations manually

If you need more control to decide when the migrations are executed it is possible to configure the application like this:

[configuration]
----
flyway:
  enabled: true
  datasources:
    default:
      enabled: false
----
- Enable Flyway and disable flyway migrations for your specific datasource

Now you can inject the `FlywayMigrator` bean and call manually the method `run` to execute the migrations when you want.
