[versions]
micronaut = "5.0.0"
micronaut-test = "5.0.0"
micronaut-logging = "2.0.0"
micronaut-platform = "5.0.0-RC1"
micronaut-serde = "3.0.0"
micronaut-data = "5.0.0"
micronaut-sql = "7.0.1"
micronaut-validation = "5.0.0"
micronaut-gradle-plugin = "5.0.0-M1"
managed-flyway = "12.6.2"
graal-svm = "25.0.3"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
managed-flyway = { module = "org.flywaydb:flyway-core", version.ref = "managed-flyway" }
managed-flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "managed-flyway" }
managed-flyway-sqlserver = { module = "org.flywaydb:flyway-sqlserver", version.ref = "managed-flyway" }
managed-flyway-oracle = { module = "org.flywaydb:flyway-database-oracle", version.ref = "managed-flyway" }
managed-flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "managed-flyway" }

graal-svm = { module = "org.graalvm.nativeimage:svm", version.ref = "graal-svm" }
micronaut-data = { module = "io.micronaut.data:micronaut-data-bom", version.ref = "micronaut-data" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }

gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }

test-containers-spock = { module = "org.testcontainers:testcontainers-spock" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
testcontainers-oracle-free = { module = "org.testcontainers:testcontainers-oracle-free" }
