Args = --features=io.micronaut.flyway.StaticResourceFeature \
       --initialize-at-build-time=io.micronaut.flyway.StaticResourceProvider \
       --initialize-at-build-time=io.micronaut.flyway.StaticResourceProvider$StaticLoadableResource
