micronaut.application.name=demo
datasources.default.db-type=oracle
datasources.default.dialect=ORACLE
datasources.default.driver-class-name=oracle.jdbc.OracleDriver
flyway.datasources.default.enabled=true
