# Micronaut Books DataSource
datasources.default.dialect=H2
datasources.default.schema-generate=NONE
flyway.datasources.default.enabled=true

# Grails Books DataSource
datasources.grails.dialect=H2
datasources.grails.schema-generate=NONE
flyway.datasources.grails.enabled=true
